// GENERATED by scripts/migration-manifest.mjs — do not edit by hand.
//
// The migrations this build of the application expects the database to have
// applied. /api/ready compares this against `_prisma_migrations` so a deploy
// that is ahead of its schema reports not-ready instead of serving pages that
// throw. Regenerate with `node scripts/migration-manifest.mjs`; CI fails if
// this file and the migration directories disagree.

/** prisma/migrations — SQLite, local development and the fast suite. */
export const SQLITE_MIGRATIONS = [
  "20260905223309_init",
  "20260906004035_hardening_audit_soft_delete_concurrency",
  "20260906120000_sessions_mfa_jobs_alerts",
  "20260910224036_import_batches",
  "20260911180035_workspace_invitations",
] as const;

/** prisma/migrations-postgres — PostgreSQL, every deployed environment. */
export const POSTGRES_MIGRATIONS = [
  "00000000000000_init",
  "20260910224119_import_batches",
  "20260911180102_workspace_invitations",
] as const;
